const ENVS = import.meta.env;

const Envs = {
    FIREBASE_API_KEY: ENVS.VITE_FIREBASE_API_KEY,
    FIREBASE_DOMAIN: ENVS.VITE_FIREBASE_DOMAIN,
    FIREBASE_PROJECT_ID: ENVS.VITE_FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: ENVS.VITE_FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: ENVS.VITE_FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID: ENVS.VITE_FIREBASE_APP_ID,
    FIREBASE_MEASUREMENT_ID: ENVS.VITE_FIREBASE_MEASUREMENT_ID,
    SENTRY_DSN: ENVS.VITE_SENTRY_DSN
};

                                      
export default Envs;